/**
 * This file content is autogenerated at contract deployment.
 * You should not edit it manually or your changes might be overwritten.
 */

export const attensysCourseAbi = [
  {
    type: "impl",
    name: "IAttenSysCourseImpl",
    interface_name: "attendsys::contracts::AttenSysCourse::IAttenSysCourse",
  },
  {
    type: "enum",
    name: "core::bool",
    variants: [
      {
        name: "False",
        type: "()",
      },
      {
        name: "True",
        type: "()",
      },
    ],
  },
  {
    type: "struct",
    name: "core::byte_array::ByteArray",
    members: [
      {
        name: "data",
        type: "core::array::Array::<core::bytes_31::bytes31>",
      },
      {
        name: "pending_word",
        type: "core::felt252",
      },
      {
        name: "pending_word_len",
        type: "core::integer::u32",
      },
    ],
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      {
        name: "low",
        type: "core::integer::u128",
      },
      {
        name: "high",
        type: "core::integer::u128",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Uri",
    members: [
      {
        name: "first",
        type: "core::felt252",
      },
      {
        name: "second",
        type: "core::felt252",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Course",
    members: [
      {
        name: "owner",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
      {
        name: "accessment",
        type: "core::bool",
      },
      {
        name: "uri",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Uri",
      },
      {
        name: "course_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "is_suspended",
        type: "core::bool",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Creator",
    members: [
      {
        name: "address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "number_of_courses",
        type: "core::integer::u256",
      },
      {
        name: "creator_status",
        type: "core::bool",
      },
    ],
  },
  {
    type: "function",
    name: "create_course",
    inputs: [
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "accessment_",
        type: "core::bool",
      },
      {
        name: "base_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "name_",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "symbol",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "course_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "add_replace_course_content",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "new_course_uri_a",
        type: "core::felt252",
      },
      {
        name: "new_course_uri_b",
        type: "core::felt252",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "finish_course_claim_certification",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "check_course_completion_status_n_certification",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
      {
        name: "candidate",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_course_infos",
    inputs: [
      {
        name: "course_identifiers",
        type: "core::array::Array::<core::integer::u256>",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysCourse::AttenSysCourse::Course>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_user_completed_courses",
    inputs: [
      {
        name: "user",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<core::integer::u256>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_courses_info",
    inputs: [],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysCourse::AttenSysCourse::Course>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_creator_courses",
    inputs: [
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysCourse::AttenSysCourse::Course>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_creator_info",
    inputs: [
      {
        name: "creator",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Creator",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_course_nft_contract",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "transfer_admin",
    inputs: [
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_admin_ownership",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_new_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_course_completions",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::integer::u256",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "ensure_admin",
    inputs: [],
    outputs: [],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_suspension_status",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "toggle_suspension",
    inputs: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
      },
      {
        name: "suspend",
        type: "core::bool",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "owner",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "_hash",
        type: "core::starknet::class_hash::ClassHash",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseCreated",
    kind: "struct",
    members: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "accessment_",
        type: "core::bool",
        kind: "data",
      },
      {
        name: "base_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "name_",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "symbol",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "course_ipfs_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseReplaced",
    kind: "struct",
    members: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "new_course_uri_a",
        type: "core::felt252",
        kind: "data",
      },
      {
        name: "new_course_uri_b",
        type: "core::felt252",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseCertClaimed",
    kind: "struct",
    members: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "candidate",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::AdminTransferred",
    kind: "struct",
    members: [
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseSuspended",
    kind: "struct",
    members: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseUnsuspended",
    kind: "struct",
    members: [
      {
        name: "course_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysCourse::AttenSysCourse::Event",
    kind: "enum",
    variants: [
      {
        name: "CourseCreated",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseCreated",
        kind: "nested",
      },
      {
        name: "CourseReplaced",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseReplaced",
        kind: "nested",
      },
      {
        name: "CourseCertClaimed",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseCertClaimed",
        kind: "nested",
      },
      {
        name: "AdminTransferred",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::AdminTransferred",
        kind: "nested",
      },
      {
        name: "CourseSuspended",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseSuspended",
        kind: "nested",
      },
      {
        name: "CourseUnsuspended",
        type: "attendsys::contracts::AttenSysCourse::AttenSysCourse::CourseUnsuspended",
        kind: "nested",
      },
    ],
  },
];
export const attensysEventAbi = [
  {
    type: "impl",
    name: "IAttenSysEventImpl",
    interface_name: "attendsys::contracts::AttenSysEvent::IAttenSysEvent",
  },
  {
    type: "struct",
    name: "core::byte_array::ByteArray",
    members: [
      {
        name: "data",
        type: "core::array::Array::<core::bytes_31::bytes31>",
      },
      {
        name: "pending_word",
        type: "core::felt252",
      },
      {
        name: "pending_word_len",
        type: "core::integer::u32",
      },
    ],
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      {
        name: "low",
        type: "core::integer::u128",
      },
      {
        name: "high",
        type: "core::integer::u128",
      },
    ],
  },
  {
    type: "enum",
    name: "core::bool",
    variants: [
      {
        name: "False",
        type: "()",
      },
      {
        name: "True",
        type: "()",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::UserAttendedEventStruct",
    members: [
      {
        name: "event_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "time",
        type: "core::integer::u256",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Time",
    members: [
      {
        name: "registration_open",
        type: "core::bool",
      },
      {
        name: "start_time",
        type: "core::integer::u256",
      },
      {
        name: "end_time",
        type: "core::integer::u256",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventStruct",
    members: [
      {
        name: "event_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "time",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Time",
      },
      {
        name: "active_status",
        type: "core::bool",
      },
      {
        name: "signature_count",
        type: "core::integer::u256",
      },
      {
        name: "event_organizer",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "registered_attendants",
        type: "core::integer::u256",
      },
      {
        name: "event_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "is_suspended",
        type: "core::bool",
      },
    ],
  },
  {
    type: "function",
    name: "create_event",
    inputs: [
      {
        name: "owner_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "event_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "base_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "name_",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "symbol",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "start_time_",
        type: "core::integer::u256",
      },
      {
        name: "end_time_",
        type: "core::integer::u256",
      },
      {
        name: "reg_status",
        type: "core::bool",
      },
      {
        name: "event_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "end_event",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "batch_certify_attendees",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "mark_attendance",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "register_for_event",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_attendance_status",
    inputs: [
      {
        name: "attendee",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_attended_events",
    inputs: [
      {
        name: "user",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysEvent::AttenSysEvent::UserAttendedEventStruct>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_list_registered_events",
    inputs: [
      {
        name: "user",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysEvent::AttenSysEvent::UserAttendedEventStruct>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "start_end_reg",
    inputs: [
      {
        name: "reg_stat",
        type: "core::bool",
      },
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_event_details",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventStruct",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_event_nft_contract",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_events",
    inputs: [],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysEvent::AttenSysEvent::EventStruct>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "transfer_admin",
    inputs: [
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_admin_ownership",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_new_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "sponsor_event",
    inputs: [
      {
        name: "event",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "amt",
        type: "core::integer::u256",
      },
      {
        name: "uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "withdraw_sponsorship_funds",
    inputs: [
      {
        name: "amt",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "toggle_event_suspended_status",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
      {
        name: "status",
        type: "core::bool",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_event_suspended_status",
    inputs: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "owner",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "_hash",
        type: "core::starknet::class_hash::ClassHash",
      },
      {
        name: "_token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "sponsorship_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Sponsor",
    kind: "struct",
    members: [
      {
        name: "amt",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "event",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Withdrawn",
    kind: "struct",
    members: [
      {
        name: "amt",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "event",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventCreated",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "event_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "event_organizer",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "event_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventEnded",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AttendanceMarked",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "attendee",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::RegisteredForEvent",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "attendee",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::RegistrationStatusChanged",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "registration_open",
        type: "core::bool",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AdminTransferred",
    kind: "struct",
    members: [
      {
        name: "old_admin",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AdminOwnershipClaimed",
    kind: "struct",
    members: [
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::BatchCertificationCompleted",
    kind: "struct",
    members: [
      {
        name: "event_identifier",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "certified_attendees",
        type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Event",
    kind: "enum",
    variants: [
      {
        name: "Sponsor",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Sponsor",
        kind: "nested",
      },
      {
        name: "Withdrawn",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::Withdrawn",
        kind: "nested",
      },
      {
        name: "EventCreated",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventCreated",
        kind: "nested",
      },
      {
        name: "EventEnded",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::EventEnded",
        kind: "nested",
      },
      {
        name: "AttendanceMarked",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AttendanceMarked",
        kind: "nested",
      },
      {
        name: "RegisteredForEvent",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::RegisteredForEvent",
        kind: "nested",
      },
      {
        name: "RegistrationStatusChanged",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::RegistrationStatusChanged",
        kind: "nested",
      },
      {
        name: "AdminTransferred",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AdminTransferred",
        kind: "nested",
      },
      {
        name: "AdminOwnershipClaimed",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::AdminOwnershipClaimed",
        kind: "nested",
      },
      {
        name: "BatchCertificationCompleted",
        type: "attendsys::contracts::AttenSysEvent::AttenSysEvent::BatchCertificationCompleted",
        kind: "nested",
      },
    ],
  },
];
export const attensysOrgAbi = [
  {
    type: "impl",
    name: "IAttenSysOrgImpl",
    interface_name: "attendsys::contracts::AttenSysOrg::IAttenSysOrg",
  },
  {
    type: "struct",
    name: "core::byte_array::ByteArray",
    members: [
      {
        name: "data",
        type: "core::array::Array::<core::bytes_31::bytes31>",
      },
      {
        name: "pending_word",
        type: "core::felt252",
      },
      {
        name: "pending_word_len",
        type: "core::integer::u32",
      },
    ],
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      {
        name: "low",
        type: "core::integer::u128",
      },
      {
        name: "high",
        type: "core::integer::u128",
      },
    ],
  },
  {
    type: "enum",
    name: "core::bool",
    variants: [
      {
        name: "False",
        type: "()",
      },
      {
        name: "True",
        type: "()",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Student",
    members: [
      {
        name: "address_of_student",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "num_of_bootcamps_registered_for",
        type: "core::integer::u256",
      },
      {
        name: "status",
        type: "core::integer::u8",
      },
      {
        name: "student_details_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Instructor",
    members: [
      {
        name: "address_of_instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "num_of_classes",
        type: "core::integer::u256",
      },
      {
        name: "name_of_org",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "organization_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Bootcamp",
    members: [
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "address_of_org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "bootcamp_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "number_of_instructors",
        type: "core::integer::u256",
      },
      {
        name: "number_of_students",
        type: "core::integer::u256",
      },
      {
        name: "number_of_all_bootcamp_classes",
        type: "core::integer::u256",
      },
      {
        name: "nft_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "active_meet_link",
        type: "core::byte_array::ByteArray",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Class",
    members: [
      {
        name: "address_of_org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "num_of_reg_students",
        type: "core::integer::u32",
      },
      {
        name: "active_status",
        type: "core::bool",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
  },
  {
    type: "struct",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Organization",
    members: [
      {
        name: "address_of_org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "number_of_instructors",
        type: "core::integer::u256",
      },
      {
        name: "number_of_students",
        type: "core::integer::u256",
      },
      {
        name: "number_of_all_classes",
        type: "core::integer::u256",
      },
      {
        name: "number_of_all_bootcamps",
        type: "core::integer::u256",
      },
      {
        name: "org_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "total_sponsorship_fund",
        type: "core::integer::u256",
      },
    ],
  },
  {
    type: "function",
    name: "create_org_profile",
    inputs: [
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "org_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "add_instructor_to_org",
    inputs: [
      {
        name: "instructor",
        type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
      },
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "remove_instructor_from_org",
    inputs: [
      {
        name: "instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "create_bootcamp",
    inputs: [
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "bootcamp_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "nft_name",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "nft_symbol",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "nft_uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "num_of_class_to_create",
        type: "core::integer::u256",
      },
      {
        name: "bootcamp_ipfs_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "add_active_meet_link",
    inputs: [
      {
        name: "meet_link",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "is_instructor",
        type: "core::bool",
      },
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "add_uploaded_video_link",
    inputs: [
      {
        name: "video_link",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "is_instructor",
        type: "core::bool",
      },
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "register_for_bootcamp",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "student_uri",
        type: "core::byte_array::ByteArray",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "approve_registration",
    inputs: [
      {
        name: "student_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "decline_registration",
    inputs: [
      {
        name: "student_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "mark_attendance_for_a_class",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "instructor_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "class_id",
        type: "core::integer::u64",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "single_certify_student",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "single_certify_student",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "students",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "setSponsorShipAddress",
    inputs: [
      {
        name: "sponsor_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "sponsor_organization",
    inputs: [
      {
        name: "organization",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "uri",
        type: "core::byte_array::ByteArray",
      },
      {
        name: "amt",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "withdraw_sponsorship_fund",
    inputs: [
      {
        name: "amt",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "suspend_organization",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "suspend",
        type: "core::bool",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "suspend_org_bootcamp",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id_",
        type: "core::integer::u64",
      },
      {
        name: "suspend",
        type: "core::bool",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_bootcamp_active_meet_link",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "core::byte_array::ByteArray",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_bootcamp_uploaded_video_link",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<core::byte_array::ByteArray>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_registration_request",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Student>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_org_instructors",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Instructor>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_org_bootcamps",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Bootcamp>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_bootcamps_on_platform",
    inputs: [],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Bootcamp>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_org_classes",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Class>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_instructor_org_classes",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Class>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_org_info",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Organization",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_org_info",
    inputs: [],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Organization>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_student_info",
    inputs: [
      {
        name: "student_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Student",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_student_classes",
    inputs: [
      {
        name: "student",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Class>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_instructor_part_of_org",
    inputs: [
      {
        name: "instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_instructor_info",
    inputs: [
      {
        name: "instructor",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::Instructor>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_bootcamp_info",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Bootcamp",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "transfer_admin",
    inputs: [
      {
        name: "new_admin",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_admin_ownership",
    inputs: [],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_new_admin",
    inputs: [],
    outputs: [
      {
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_org_sponsorship_balance",
    inputs: [
      {
        name: "organization",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::integer::u256",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_bootcamp_suspended",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_org_suspended",
    inputs: [
      {
        name: "org_",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_registered_bootcamp",
    inputs: [
      {
        name: "student",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::RegisteredBootcamp>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_specific_organization_registered_bootcamp",
    inputs: [
      {
        name: "org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "student",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<attendsys::contracts::AttenSysOrg::AttenSysOrg::RegisteredBootcamp>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_class_attendance_status",
    inputs: [
      {
        name: "org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "class_id",
        type: "core::integer::u64",
      },
      {
        name: "student",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_all_bootcamp_classes",
    inputs: [
      {
        name: "org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<core::integer::u64>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_certified_student_bootcamp_address",
    inputs: [
      {
        name: "org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
    ],
    outputs: [
      {
        type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_bootcamp_certification_status",
    inputs: [
      {
        name: "org",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
      },
      {
        name: "student",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::bool",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "admin",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "class_hash",
        type: "core::starknet::class_hash::ClassHash",
      },
      {
        name: "_token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "sponsorship_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Sponsor",
    kind: "struct",
    members: [
      {
        name: "amt",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "organization",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Withdrawn",
    kind: "struct",
    members: [
      {
        name: "amt",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "organization",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationProfile",
    kind: "struct",
    members: [
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "org_ipfs_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::InstructorAddedToOrg",
    kind: "struct",
    members: [
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "instructor",
        type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
        kind: "key",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::InstructorRemovedFromOrg",
    kind: "struct",
    members: [
      {
        name: "instructor_addr",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "org_owner",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootCampCreated",
    kind: "struct",
    members: [
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "bootcamp_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "nft_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "nft_symbol",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "nft_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "num_of_classes",
        type: "core::integer::u256",
        kind: "data",
      },
      {
        name: "bootcamp_ipfs_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::ActiveMeetLinkAdded",
    kind: "struct",
    members: [
      {
        name: "meet_link",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
      {
        name: "is_instructor",
        type: "core::bool",
        kind: "data",
      },
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::VideoLinkUploaded",
    kind: "struct",
    members: [
      {
        name: "video_link",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "is_instructor",
        type: "core::bool",
        kind: "data",
      },
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootcampRegistration",
    kind: "struct",
    members: [
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::RegistrationApproved",
    kind: "struct",
    members: [
      {
        name: "student_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::RegistrationDeclined",
    kind: "struct",
    members: [
      {
        name: "student_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::AttendanceMarked",
    kind: "struct",
    members: [
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "instructor_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "class_id",
        type: "core::integer::u64",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::StudentsCertified",
    kind: "struct",
    members: [
      {
        name: "org_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "class_id",
        type: "core::integer::u64",
        kind: "data",
      },
      {
        name: "student_addresses",
        type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::SponsorshipAddressSet",
    kind: "struct",
    members: [
      {
        name: "sponsor_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationSponsored",
    kind: "struct",
    members: [
      {
        name: "organization_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "sponsor_uri",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "sponsorship_amount",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::SponsorshipFundWithdrawn",
    kind: "struct",
    members: [
      {
        name: "withdrawal_amount",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationSuspended",
    kind: "struct",
    members: [
      {
        name: "org_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "org_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "suspended",
        type: "core::bool",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootCampSuspended",
    kind: "struct",
    members: [
      {
        name: "org_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "bootcamp_id",
        type: "core::integer::u64",
        kind: "data",
      },
      {
        name: "bootcamp_name",
        type: "core::byte_array::ByteArray",
        kind: "data",
      },
      {
        name: "suspended",
        type: "core::bool",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Event",
    kind: "enum",
    variants: [
      {
        name: "Sponsor",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Sponsor",
        kind: "nested",
      },
      {
        name: "Withdrawn",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::Withdrawn",
        kind: "nested",
      },
      {
        name: "OrganizationProfile",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationProfile",
        kind: "nested",
      },
      {
        name: "InstructorAddedToOrg",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::InstructorAddedToOrg",
        kind: "nested",
      },
      {
        name: "InstructorRemovedFromOrg",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::InstructorRemovedFromOrg",
        kind: "nested",
      },
      {
        name: "BootCampCreated",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootCampCreated",
        kind: "nested",
      },
      {
        name: "ActiveMeetLinkAdded",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::ActiveMeetLinkAdded",
        kind: "nested",
      },
      {
        name: "VideoLinkUploaded",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::VideoLinkUploaded",
        kind: "nested",
      },
      {
        name: "BootcampRegistration",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootcampRegistration",
        kind: "nested",
      },
      {
        name: "RegistrationApproved",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::RegistrationApproved",
        kind: "nested",
      },
      {
        name: "RegistrationDeclined",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::RegistrationDeclined",
        kind: "nested",
      },
      {
        name: "AttendanceMarked",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::AttendanceMarked",
        kind: "nested",
      },
      {
        name: "StudentsCertified",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::StudentsCertified",
        kind: "nested",
      },
      {
        name: "SponsorshipAddressSet",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::SponsorshipAddressSet",
        kind: "nested",
      },
      {
        name: "OrganizationSponsored",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationSponsored",
        kind: "nested",
      },
      {
        name: "SponsorshipFundWithdrawn",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::SponsorshipFundWithdrawn",
        kind: "nested",
      },
      {
        name: "OrganizationSuspended",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::OrganizationSuspended",
        kind: "nested",
      },
      {
        name: "BootCampSuspended",
        type: "attendsys::contracts::AttenSysOrg::AttenSysOrg::BootCampSuspended",
        kind: "nested",
      },
    ],
  },
];
export const attensysSponsorAbi = [
  {
    type: "impl",
    name: "AttenSysSponsorImpl",
    interface_name: "attendsys::contracts::AttenSysSponsor::IAttenSysSponsor",
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      {
        name: "low",
        type: "core::integer::u128",
      },
      {
        name: "high",
        type: "core::integer::u128",
      },
    ],
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      {
        name: "sender",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "amount",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "amount",
        type: "core::integer::u256",
      },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_contract_balance",
    inputs: [
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
    outputs: [
      {
        type: "core::integer::u256",
      },
    ],
    state_mutability: "view",
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "organization_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "event_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysSponsor::AttenSysSponsor::SponsorDeposited",
    kind: "struct",
    members: [
      {
        name: "token",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "amount",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysSponsor::AttenSysSponsor::TokenWithdraw",
    kind: "struct",
    members: [
      {
        name: "token",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "amount",
        type: "core::integer::u256",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "attendsys::contracts::AttenSysSponsor::AttenSysSponsor::Event",
    kind: "enum",
    variants: [
      {
        name: "SponsorDeposited",
        type: "attendsys::contracts::AttenSysSponsor::AttenSysSponsor::SponsorDeposited",
        kind: "nested",
      },
      {
        name: "TokenWithdraw",
        type: "attendsys::contracts::AttenSysSponsor::AttenSysSponsor::TokenWithdraw",
        kind: "nested",
      },
    ],
  },
];
