/**
 * This file content is autogenerated at contract deployment.
 * You should not edit it manually or your changes might be overwritten.
 */

export const attensysCourseAddress =
  "0x6225e51e811fd3a05d03508606e8c366eda87be96efe22c553c06885ff6fa25";
export const attensysEventAddress =
  "0x54620c695dce26e04cf0f610fd1d7431bbe8c285c44b4abb49e8d7278526511";
export const attensysOrgAddress =
  "0x4151002ea179e8721142f2a63c90aae8d5ed787cc60624cc882c5bba42c1700";
export const attensysSponsorAddress =
  "0x651dc203f937155b0062e1b2bfd96eeee2a203124d8611e2420160c3dfa3756";
