/**
 * This file content is autogenerated at contract deployment.
 * You should not edit it manually or your changes might be overwritten.
 */

export const attensysCourseAddress =
  "0x3d82403c11c5397ea3faa3cd5255a5cf5fe94fa07c061664292c3a93ff6ca25";
export const attensysEventAddress =
  "0x594a29483f36e096d3a020d4edf7bac8c827223f309393408d87596444e0fe0";
export const attensysOrgAddress =
  "0x29232fcaed22ab905efe09c83fd28959c05fbb09a67dbe496f0f8027f5dd6e7";
export const attensysSponsorAddress =
  "0x5ce70be6688646b33131bb5563ee60aa9b4ebcb4efcf848998defa14afe8893";
