/**
 * This file content is autogenerated at contract deployment.
 * You should not edit it manually or your changes might be overwritten.
 */

export const attensysCourseAddress =
  "0x3998e1204bb01afc5abb67c154647af70d489a3b0cb012b99e7df65f6c9d93b";
export const attensysEventAddress =
  "0x6b52afeddb6f15bacaece0898988ea9fe9d013ed66b548b06be6e1e45ba0971";
export const attensysOrgAddress =
  "0x54257d73928ecb40758d5a27ef99ef237d565bfaeadb1d00b939bf27fbc067a";
export const attensysSponsorAddress =
  "0x6e79a1bb1e0e64deb6ea7f44217e4d682f33125296c16872fce3273047d4802";
