import tester from "@/assets/tester.svg"
import ramp from "@/assets/ramp.svg"
import banx from "@/assets/banxa.svg"

import saibat from "@/assets/saiibatu.svg"

import stunt from "@/assets/stunts.png"
import social from "@/assets/social.png"
import grapic from "@/assets/graphics.png"
import last from "@/assets/last.jpg"
import Orange from "@/assets/Orange.svg"
import summer from "@/assets/summer.png"
import sunder from "@/assets/summer.png"

export const guestdata = [
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
]

export const attendanceData = [
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: false,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
]

export const approvedsponsors = [
  {
    icon: tester,
    name: "Cryptotesters",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
  {
    icon: ramp,
    name: "Ramp",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
]

export const pendingsponsors = [
  {
    icon: banx,
    name: "Banxa",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
  {
    icon: ramp,
    name: "Ramp",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
]

export const HighlightData = [
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: saibat,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: stunt,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: social,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: grapic,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: last,
  },
]

export const allEventData = [
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
]

export const explorerData = [
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
]

export const eventsData = [
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
]

export const gridsData = [
  {
    name: "Event",
    subProp: [
      "Key",
      "Status",
      "Registered events",
      "Marked attendance",
      "Certifications",
    ],
    viewPartName: "All Events",
    heading: [
      "Event Name",
      "Attendance status",
      "Certifications",
      "Date registered",
    ],
    eventsData: [
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
    ],
  },
  {
    name: "Courses",
    subProp: ["Key", "Status", "Courses", "Completed courses", "Ongoing"],
    viewPartName: "All Courses",
    heading: [
      "Course Name",
      "Completion status",
      "Certifications",
      "Organization",
    ],
    eventsData: [
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
    ],
  },
  {
    name: "Certifications",
    subProp: [
      "Key",
      "Status",
      "Course Certification",
      "Event Certification",
      "Total",
    ],
    viewPartName: "All Certifications",
    heading: ["Activity type", "Completion status", "Certifications", "Issuer"],
    eventsData: [
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
    ],
  },
]
