import tester from "@/assets/tester.svg"
import ramp from "@/assets/ramp.svg"
import banx from "@/assets/banxa.svg"

import saibat from "@/assets/saiibatu.svg"

import stunt from "@/assets/stunts.png"
import social from "@/assets/social.png"
import grapic from "@/assets/graphics.png"
import last from "@/assets/last.jpg"
import Orange from "@/assets/Orange.svg"
import summer from "@/assets/summer.png"
import sunder from "@/assets/summer.png"
import companylogo from "@/assets/companylogo.svg"
import bootcamp1 from "@/assets/project.svg"
import bootcamp2 from "@/assets/graphicsdesign.svg"
import bootcamp3 from "@/assets/flier.svg"
import bootcamp4 from "@/assets/effects.png"
import testlogo from "@/assets/testlogo.svg"
import handshake from "@/assets/handshake.svg"
import world from "@/assets/world.svg"
import skip from "@/assets/skipp.svg"
import pattern from "@/assets/pattern.svg"
import lolli from "@/assets/lolli.svg"
import domino from "@/assets/domino.svg"
import robotimg from "@/assets/roboy.png"
import courseImg from "@/assets/videoImg.svg"
import podcast from "@/assets/podcast.svg"
import youtube from "@/assets/youtube.svg"

export const skills = [
  "Design",
  "Development",
  "Marketing",
  "Health & Fitness",
  "Business",
  "IT & Software",
  "Crypto",
  "Artificial Intelligence",
  "Product Management",
]
export const subLectures = [
  {
    img: courseImg,
    title: "What is web development?",
    time: "8 min",
    desc: "An introduction to the world of web development, covering the basics of how websites...",
  },
  {
    img: youtube,
    title: "Blockchain development: from Zero to Hero",
    time: "8 min",
    desc: "An introduction to the world of web development, covering the basics of how websites...",
  },
  {
    img: podcast,
    title: "Start forex trading today",
    time: "8 min",
    desc: "An introduction to the world of web development, covering the basics of how websites...",
  },
]

export const guestdata = [
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Taiwo",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
  },
]

export const attendanceData = [
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: false,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
  {
    name: "Akinbola Kehinde",
    address: "1Lbcfr7...ZnX71",
    status: "Approved",
    role: "N/A",
    date: "12/25/2024",
    checkstat: true,
  },
]

export const approvedsponsors = [
  {
    icon: tester,
    name: "Cryptotesters",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
  {
    icon: ramp,
    name: "Ramp",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
]

export const pendingsponsors = [
  {
    icon: banx,
    name: "Banxa",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
  {
    icon: ramp,
    name: "Ramp",
    amount: 1000,
    address: "0x5c956e61...de5232dc11",
    time: "11 OCT, 2024   |  10:25 PM",
  },
]

export const HighlightData = [
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: saibat,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: stunt,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: social,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: grapic,
  },
  {
    name: "The Ari Experience",
    time: "Wed, Oct 30,4pm",
    image: last,
  },
]

export const allEventData = [
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: Orange,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: saibat,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: stunt,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: social,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: grapic,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: last,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: sunder,
  },
  {
    name: "TechXperience UK",
    hall: "Shoprite Ikeja City Mall",
    city: "Ikeja, Lagos",
    date: "Saturday, October 12",
    time: "8:30 AM - 9:30 AM",
    fee: "10",
    image: summer,
  },
]

export const explorerData = [
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just registered for an event ",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Blockchain Fundamentals",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This User just created a course",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Intro to NFTs",
  },
  {
    address: "1Lbcfr7...ZnX71",
    status: "This user just got Certified",
    timestamp: "11 OCT, 2024   |  10:25 PM",
    category: "Crypto Academy Bootcamp",
  },
]

export const eventsData = [
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "3 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "2 mon",
  },
  {
    eventName: "Blockchain Africa ‘24",
    status: "Attendance Verified",
    certification: "View certifications",
    nftImg: "",
    date: "1 mon",
  },
]

export const gridsData = [
  {
    name: "Event",
    subProp: [
      "Key",
      "Status",
      "Registered events",
      "Marked attendance",
      "Certifications",
    ],
    viewPartName: "All Events",
    heading: [
      "Event Name",
      "Attendance status",
      "Certifications",
      "Date registered",
    ],
    eventsData: [
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "3 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "2 mon",
      // },
      // {
      //   eventName: "Blockchain Africa ‘24",
      //   status: "Attendance Verified",
      //   certification: "View certifications",
      //   nftImg: "",
      //   date: "1 mon",
      // },
    ],
  },
  {
    name: "Courses",
    subProp: ["Key", "Status", "Courses", "Completed courses", "Ongoing"],
    viewPartName: "All Courses",
    heading: [
      "Course Name",
      "Completion status",
      "Certifications",
      "Organization",
    ],
    eventsData: [
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
    ],
  },
  {
    name: "Certifications",
    subProp: [
      "Key",
      "Status",
      "Course Certification",
      "Event Certification",
      "Total",
    ],
    viewPartName: "All Certifications",
    heading: ["Activity type", "Completion status", "Certifications", "Issuer"],
    eventsData: [
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Introduction to Dev-ops",
        status: "Course Complete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
      {
        eventName: "Dev-ops Soft landing 2.0",
        status: "Incomplete",
        certification: "View certifications",
        nftImg: "",
        date: "BCK Web3 Pro",
      },
    ],
  },
]

export const caroselldata = [
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp1,
  },
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp2,
  },
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp3,
  },
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp1,
  },
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp2,
  },
  {
    name: "Web3 Afrika bootcamp",
    time: "From 12th Nov - 15th Nov 2024",
    logo: companylogo,
    flier: bootcamp3,
  },
]

export const organizationData = [
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 4,
    reviewnumber: "300",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: handshake,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 3,
    reviewnumber: "281",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: world,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 5,
    reviewnumber: "1000",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: skip,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 5,
    reviewnumber: "381",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: pattern,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 3,
    reviewnumber: "28",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: lolli,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 5,
    reviewnumber: "21",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: domino,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 5,
    reviewnumber: "381",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: pattern,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 3,
    reviewnumber: "28",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: lolli,
  },
  {
    name: "Orangutan Edu Academy",
    about:
      "Orangutan Edu Academy offers in-depth blockchain courses and certifications",
    bootcampnumber: "3",
    instructors: "21",
    stars: 5,
    reviewnumber: "21",
    tags: ["blockchain", "web3", "technology", "Crypto"],
    logo: testlogo,
    flier: domino,
  },
]

export const favoriteCourseData = [
  {
    coursetitle: " Elementary UI",
    organizationname: "  Tech Innovators Academy",
    numberofstudents: 1220,
    instructor: "Akinbola kehinde",
    flier: domino,
    stars: 4,
  },
  {
    coursetitle: " Elementary UI",
    organizationname: "  Tech Innovators Academy",
    numberofstudents: 1220,
    instructor: "Akinbola kehinde",
    flier: lolli,
    stars: 5,
  },
  {
    coursetitle: " Elementary UI",
    organizationname: "  Tech Innovators Academy",
    numberofstudents: 1220,
    instructor: "Akinbola kehinde",
    flier: pattern,
    stars: 3,
  },
  {
    coursetitle: " Elementary UI",
    organizationname: "  Tech Innovators Academy",
    numberofstudents: 1220,
    instructor: "Akinbola kehinde",
    flier: robotimg,
    stars: 4,
  },
]


export const permisiondata = [
  {
    email : "vladamirocks@gmail.com",
    address : "0x5c956e61...de5232dc11",
    access : ["Owner", "Instructor"]
  },
  {
    email : "kenzman@gmail.com",
    address : "0x5c956e61...de5232dc11",
    access : ["Instructor"]
  },
  {
    email : "ephraim@gmail.com",
    address : "0x5c956e61...de5232dc11",
    access : ["Instructor"]
  },
]

export const registereddata = [
  {
    email : "vladamirocks@gmail.com",
    address : "0x5c956e61...de5232dc11",
   registeredbootcamp : 3,
   certifications : 3,
   joined: 3,
  },
  {
    email : "kenzman@gmail.com",
    address : "0x5c956e61...de5232dc11",
   registeredbootcamp : 2,
   certifications : 6,
   joined: 1,
  },
  {
    email : "ephraim@gmail.com",
    address : "0x5c956e61...de5232dc11",
   registeredbootcamp : 3,
   certifications : 3,
   joined: 3,
  },
]