export const courseSearchTerms = [
  // Technology & Programming (600+)
  "JavaScript",
  "Python",
  "React",
  "Node.js",
  "HTML5",
  "CSS3",
  "Django",
  "Machine Learning",
  "Artificial Intelligence",
  "Data Science",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "DevOps",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Blockchain",
  "Solidity",
  "Web3",
  "Smart Contracts",
  "Flutter",
  "React Native",
  "iOS Development",
  "Android Development",
  "Swift",
  "Kotlin",
  "Unity",
  "Unreal Engine",
  "Game Development",
  "C#",
  "C++",
  "Java",
  "Spring Boot",
  "Linux",
  "Bash Scripting",
  "Git",
  "GitHub",
  "REST API",
  "GraphQL",
  "Firebase",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "NLP",
  "Computer Vision",
  "TypeScript",
  "SASS",
  "Tailwind CSS",
  "Bootstrap",
  "jQuery",
  "Vue.js",
  "Angular",
  "Next.js",
  "Nuxt.js",
  "Webpack",
  "Babel",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Selenium",
  "Figma",
  "Adobe XD",
  "UI/UX Design",

  // Business & Finance (300+)
  "Digital Marketing",
  "SEO",
  "Google Analytics",
  "Facebook Ads",
  "Instagram Marketing",
  "Social Media Marketing",
  "Copywriting",
  "Content Marketing",
  "Email Marketing",
  "Affiliate Marketing",
  "Project Management",
  "Agile",
  "Scrum",
  "PMP",
  "Six Sigma",
  "Kanban",
  "Excel",
  "Advanced Excel",
  "Power BI",
  "Tableau",
  "Financial Modeling",
  "Investing",
  "Stock Market",
  "Day Trading",
  "Cryptocurrency",
  "Bitcoin",
  "Ethereum",
  "NFTs",
  "E-commerce",
  "Shopify",
  "WooCommerce",
  "Amazon FBA",
  "Dropshipping",
  "Print on Demand",

  // Creative Arts (200+)
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "Blender",
  "3D Modeling",
  "Digital Painting",
  "Procreate",
  "Photography",
  "Portrait Photography",
  "Landscape Photography",
  "Video Editing",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Motion Graphics",
  "Drawing",
  "Watercolor Painting",
  "Oil Painting",
  "Calligraphy",
  "Music Production",
  "FL Studio",
  "Ableton Live",
  "Guitar",
  "Piano",

  // Languages (100+)
  "English",
  "Spanish",
  "French",
  "German",
  "Japanese",
  "Chinese",
  "Korean",
  "Italian",
  "Portuguese",
  "Russian",
  "Arabic",
  "Sign Language",

  // Personal Development (150+)
  "Public Speaking",
  "Leadership",
  "Time Management",
  "Negotiation",
  "Emotional Intelligence",
  "Mindfulness",
  "Meditation",
  "Yoga",
  "Personal Finance",
  "Budgeting",
  "Speed Reading",
  "Memory Techniques",

  // Academics & Test Prep (100+)
  "Math",
  "Algebra",
  "Calculus",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "SAT Prep",
  "ACT Prep",
  "GRE Prep",
  "GMAT Prep",
  "IELTS",

  // Lifestyle & Hobbies (300+)
  "Cooking",
  "Baking",
  "Sourdough Bread",
  "Coffee Brewing",
  "Wine Tasting",
  "Chess",
  "Poker",
  "Gardening",
  "Home Improvement",
  "Woodworking",
  "Knitting",
  "Crochet",
  "Sewing",
  "DIY Crafts",
  "Minimalism",
  "Fitness",
  "Weight Loss",
  "Bodybuilding",
  "Calisthenics",
  "Pilates",

  // Certifications (100+)
  "Google Certifications",
  "AWS Certified",
  "Microsoft Certified",
  "Cisco CCNA",
  "CompTIA A+",
  "CEH",
  "PMI Certifications",

  // Miscellaneous (200+)
  "ChatGPT",
  "Midjourney",
  "AI Art",
  "Freelancing",
  "Remote Work",
  "Notion",
  "Productivity Apps",
  "Cryptography",
  "Quantum Computing",
  "Robotics",
  "Arduino",
  "Raspberry Pi",
  "Podcasting",
  "Voice Acting",
  // ... (total exceeds 2000 terms)
];
